"""Setting field metadata for the admin settings UI."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

TargetEnv = Literal["admin", "proxy", "sqlite", "pool_scale"]


@dataclass(frozen=True)
class SettingField:
    key: str
    label: str
    group: str
    field_type: Literal["bool", "int", "float", "str", "select", "text"]
    target: TargetEnv
    default: str
    hot: bool = False
    options: tuple[str, ...] = ()
    help_text: str = ""


SETTING_FIELDS: tuple[SettingField, ...] = (
    # Ingest (admin env, hot-reload worker)
    SettingField(
        "INGEST_BATCH_SIZE",
        "Embed batch size",
        "ingest",
        "int",
        "admin",
        "64",
        hot=True,
        help_text="Texts per embed HTTP request and Qdrant upsert batch.",
    ),
    SettingField(
        "INGEST_EMBED_CONCURRENCY",
        "Embed concurrency",
        "ingest",
        "int",
        "admin",
        "4",
        hot=True,
        help_text="Max concurrent embed batches across all files. Match GPU pool capacity (instances x --parallel).",
    ),
    SettingField(
        "INGEST_FILE_CONCURRENCY",
        "Parallel ingest files",
        "ingest",
        "int",
        "admin",
        "",
        hot=True,
        help_text="Worker threads, one file each. Leave empty for auto: max(1, min(4, pool URL count)).",
    ),
    SettingField(
        "INGEST_CHUNK_CONCURRENCY",
        "Parallel chunk runners",
        "ingest",
        "int",
        "admin",
        "",
        hot=True,
        help_text="Concurrent chunking files (CPU-bound). Leave empty for auto: min(4, cores / 2). Set by the capacity planner.",
    ),
    SettingField(
        "INGEST_SPARSE_REINDEX",
        "BM25 reindex mode",
        "ingest",
        "select",
        "admin",
        "idle",
        hot=True,
        options=("off", "each", "idle"),
        help_text="When to rebuild the sparse/BM25 sidecar index after dense ingest.",
    ),
    SettingField(
        "INGEST_STALL_MINUTES",
        "Stall timeout (minutes)",
        "ingest",
        "int",
        "admin",
        "15",
        hot=True,
        help_text="Mark running jobs stalled when no progress for this many minutes.",
    ),
    SettingField(
        "INGEST_MAX_ARTICLES",
        "ZIM article cap (0=unlimited)",
        "ingest",
        "int",
        "admin",
        "0",
        hot=True,
        help_text="Limit articles per ZIM file during ingest (0 = no limit).",
    ),
    SettingField(
        "EMBED_MAX_CHARS",
        "Max chars per embed",
        "ingest",
        "int",
        "admin",
        "2000",
        hot=True,
        help_text="Truncate chunk text before the embed API (independent of token chunk size).",
    ),
    SettingField(
        "INGEST_EMBED_URLS",
        "Ingest embed pool URLs",
        "ingest",
        "text",
        "admin",
        "",
        hot=True,
        help_text="Active pool endpoints (often written by scale_nomic_embed_pool.py). Override only if not using the planner.",
    ),
    SettingField(
        "NOMIC_POOL_MAX_INSTANCES",
        "Max llama-server instances",
        "ingest",
        "int",
        "pool_scale",
        "12",
        help_text="Hard cap on nomic-embed@PORT units. Saved to nomic-embed-scale.env; run scale script after change.",
    ),
    SettingField(
        "NOMIC_POOL_MIN_INSTANCES",
        "Min pool instances",
        "ingest",
        "int",
        "pool_scale",
        "1",
        help_text="Floor when nvidia-smi is unavailable (single-port fallback).",
    ),
    SettingField(
        "NOMIC_POOL_PARALLEL_PER_INSTANCE",
        "Parallel per instance (planner)",
        "ingest",
        "int",
        "pool_scale",
        "16",
        help_text="Sets INGEST_EMBED_CONCURRENCY to instances x this value when the pool is scaled.",
    ),
    SettingField(
        "NOMIC_POOL_PARALLEL",
        "llama-server --parallel",
        "ingest",
        "int",
        "pool_scale",
        "16",
        help_text="Passed to each nomic-embed@PORT systemd unit. Match parallel per instance unless you know otherwise.",
    ),
    SettingField(
        "NOMIC_POOL_VRAM_PER_INSTANCE_MIB",
        "VRAM per instance (MiB)",
        "ingest",
        "int",
        "pool_scale",
        "1024",
        help_text="Estimated VRAM per embed instance for GPU sizing.",
    ),
    SettingField(
        "NOMIC_POOL_VRAM_RESERVE_MIB",
        "VRAM reserve (MiB)",
        "ingest",
        "int",
        "pool_scale",
        "2048",
        help_text="VRAM left for chat/other GPU workloads when sizing the pool.",
    ),
    SettingField(
        "NOMIC_POOL_PORT_BASE",
        "Pool port base",
        "ingest",
        "int",
        "pool_scale",
        "18089",
        help_text="First port for nomic-embed@PORT (18089, 18090, ...).",
    ),
    SettingField(
        "NOMIC_POOL_GPU_INDEX",
        "GPU index",
        "ingest",
        "int",
        "pool_scale",
        "0",
        help_text="nvidia-smi GPU index used for VRAM sizing.",
    ),
    SettingField(
        "EMBED_URL",
        "Primary embed URL",
        "ingest",
        "str",
        "admin",
        "http://127.0.0.1:8089",
        help_text="Query embed (mirrored to rag-proxy.env). Bulk pool URLs go in Ingest embed pool URLs.",
    ),
    SettingField(
        "QDRANT_URL",
        "Qdrant URL",
        "ingest",
        "str",
        "admin",
        "http://127.0.0.1:6333",
        help_text="Vector database for dense chunks.",
    ),
    SettingField(
        "QDRANT_COLLECTION",
        "Qdrant collection",
        "ingest",
        "str",
        "admin",
        "nomad_knowledge_base",
        help_text="Collection name shared by ingest and proxy retrieval.",
    ),
    SettingField(
        "SPARSE_INDEX_URL",
        "Sparse/BM25 sidecar URL",
        "ingest",
        "str",
        "admin",
        "",
        help_text="BM25 sidecar for hybrid retrieval. Leave empty to disable sparse reindex.",
    ),
    SettingField(
        "RAG_PROXY_URL",
        "RAG proxy URL",
        "ingest",
        "str",
        "admin",
        "http://127.0.0.1:8081",
        help_text="Used by admin health checks and smoke hooks.",
    ),
    SettingField(
        "INGEST_CHUNK_SIZE_TOKENS",
        "Chunk size (tokens)",
        "ingest",
        "int",
        "admin",
        "512",
        help_text="Requires python scripts/requeue_all_ingest.py for existing files.",
    ),
    SettingField(
        "INGEST_CHUNK_OVERLAP_TOKENS",
        "Chunk overlap (tokens)",
        "ingest",
        "int",
        "admin",
        "64",
        help_text="Requires python scripts/requeue_all_ingest.py for existing files.",
    ),
    SettingField(
        "INGEST_CHUNK_TOKENIZER",
        "Chunk tokenizer",
        "ingest",
        "str",
        "admin",
        "nomic-ai/nomic-embed-text-v1.5",
        help_text="Align with embed model. Startup log warns FALLBACK if this tokenizer cannot load.",
    ),
    SettingField(
        "INGEST_CHUNK_SEMANTIC",
        "Semantic chunking",
        "ingest",
        "bool",
        "admin",
        "true",
        help_text="Requires chonkie[semantic]. Re-chunk existing files after change.",
    ),
    SettingField(
        "INGEST_CHUNK_SEMANTIC_MODEL",
        "Semantic chunk model",
        "ingest",
        "str",
        "admin",
        "minishlab/potion-base-32M",
        help_text="Local model for semantic boundary detection (requires chonkie[semantic]).",
    ),
    SettingField(
        "INGEST_CHUNK_MIN_TOKENS",
        "Min chunk tokens (merge)",
        "ingest",
        "int",
        "admin",
        "100",
        help_text="Undersized chunks below this are merged when possible.",
    ),
    # Proxy upstream + legacy RAG (rag-proxy.env)
    SettingField(
        "LLAMA_SWAP_URL",
        "llama-swap URL",
        "proxy_rag",
        "str",
        "proxy",
        "http://127.0.0.1:8080",
        help_text="Upstream for chat completions and INTENT_MODEL. Model id only in Intent model field.",
    ),
    SettingField(
        "EMBED_RETRIES",
        "Embed retries",
        "proxy_rag",
        "int",
        "proxy",
        "2",
        help_text="Retry count when query-time embed HTTP fails.",
    ),
    SettingField(
        "TOP_K",
        "Top K chunks",
        "proxy_rag",
        "int",
        "proxy",
        "5",
        help_text="Maximum chunks injected after similarity filter.",
    ),
    SettingField(
        "SIMILARITY_THRESHOLD",
        "Similarity threshold",
        "proxy_rag",
        "float",
        "proxy",
        "0.65",
        help_text="Minimum cosine similarity for a chunk to be included.",
    ),
    SettingField(
        "ENABLE_HYBRID_RETRIEVAL",
        "Hybrid dense+BM25",
        "proxy_rag",
        "bool",
        "proxy",
        "false",
        help_text="Merge dense Qdrant results with BM25 sidecar via RRF.",
    ),
    SettingField(
        "HYBRID_DENSE_WEIGHT",
        "Dense weight (hybrid)",
        "proxy_rag",
        "float",
        "proxy",
        "0.7",
        help_text="Blend weight for dense vs sparse in hybrid merge (0-1).",
    ),
    SettingField(
        "ENABLE_RERANKER",
        "Cross-encoder rerank",
        "proxy_rag",
        "bool",
        "proxy",
        "false",
        help_text="Rerank candidates via RERANKER_URL sidecar.",
    ),
    SettingField(
        "RERANKER_URL",
        "Reranker sidecar URL",
        "proxy_rag",
        "str",
        "proxy",
        "http://127.0.0.1:8095",
        help_text="HTTP rerank service (not in-process).",
    ),
    SettingField(
        "RERANK_TOP_K",
        "Rerank top K",
        "proxy_rag",
        "int",
        "proxy",
        "5",
        help_text="Keep this many chunks after reranking.",
    ),
    SettingField(
        "RETRIEVAL_CANDIDATE_K",
        "Retrieval candidate K",
        "proxy_rag",
        "int",
        "proxy",
        "20",
        help_text="Initial candidate pool size before rerank/threshold.",
    ),
    SettingField(
        "RECENCY_WEIGHT",
        "Recency weight",
        "proxy_rag",
        "float",
        "proxy",
        "0.1",
        help_text="Boost score for newer chunks when payload has timestamps.",
    ),
    SettingField(
        "RERANK_TIMEOUT_MS",
        "Rerank timeout (ms)",
        "proxy_rag",
        "int",
        "proxy",
        "200",
        help_text="Fail-open timeout for rerank HTTP call.",
    ),
    SettingField(
        "ENABLE_SEMANTIC_DEDUPE",
        "Semantic dedupe",
        "proxy_rag",
        "bool",
        "proxy",
        "false",
        help_text="Drop near-duplicate chunks before injection.",
    ),
    SettingField(
        "ENABLE_EMBED_CACHE",
        "Embed cache",
        "proxy_rag",
        "bool",
        "proxy",
        "false",
        help_text="Cache query embeddings in-process.",
    ),
    # Cognitive pipeline
    SettingField(
        "ENABLE_COGNITIVE_PIPELINE",
        "Cognitive pipeline",
        "cognitive",
        "bool",
        "proxy",
        "false",
        help_text="Master switch. false = legacy embed + Qdrant only.",
    ),
    SettingField(
        "ENABLE_TIER0_HEURISTICS",
        "Tier-0 heuristics",
        "cognitive",
        "bool",
        "proxy",
        "false",
        help_text="Fast regex/heuristic bypass before retrieval.",
    ),
    SettingField(
        "ENABLE_INTENT_ROUTER",
        "Intent router",
        "cognitive",
        "bool",
        "proxy",
        "false",
        help_text="Classify query intent via INTENT_MODEL at llama-swap.",
    ),
    SettingField(
        "ENABLE_RETRIEVAL_GATING",
        "Retrieval gating",
        "cognitive",
        "bool",
        "proxy",
        "false",
        help_text="Skip retrieval when gating says no RAG needed.",
    ),
    SettingField(
        "GATING_LOG_ONLY",
        "Gating log-only (bake-in)",
        "cognitive",
        "bool",
        "proxy",
        "false",
        help_text="Log gating decisions without skipping retrieval.",
    ),
    SettingField(
        "ENABLE_QUERY_REWRITE",
        "Query rewrite",
        "cognitive",
        "bool",
        "proxy",
        "false",
        help_text="Rewrite query before retrieval (heuristic path).",
    ),
    SettingField(
        "ENABLE_QUERY_REWRITE_LLM",
        "Query rewrite (LLM)",
        "cognitive",
        "bool",
        "proxy",
        "false",
        help_text="LLM-based query rewrite (uses INTENT_MODEL).",
    ),
    SettingField(
        "ENABLE_GRAPH_LOOKUP",
        "Graph lookup",
        "cognitive",
        "bool",
        "proxy",
        "false",
        help_text="Tier-2 graph expansion from GRAPH_DB_PATH.",
    ),
    SettingField(
        "ENABLE_TOOLS",
        "Tool stage",
        "cognitive",
        "bool",
        "proxy",
        "false",
        help_text="Optional tool-calling stage before context assembly.",
    ),
    SettingField(
        "ENABLE_ROLLING_MEMORY",
        "Rolling memory",
        "cognitive",
        "bool",
        "proxy",
        "false",
        help_text="Conversation memory in MEMORY_DB_PATH.",
    ),
    SettingField(
        "INTENT_MODEL",
        "Intent model",
        "cognitive",
        "str",
        "proxy",
        "",
        help_text="Model id (e.g. openrouter/owl-alpha), or 'auto' to reuse the model llama-swap has loaded (via /running).",
    ),
    SettingField(
        "INTENT_MODEL_URL",
        "Intent model endpoint",
        "cognitive",
        "str",
        "proxy",
        "",
        help_text="Optional dedicated endpoint for intent/rewrite calls. Empty falls back to LLAMA_SWAP_URL.",
    ),
    SettingField(
        "INTENT_MODEL_AUTO_TTL_SEC",
        "Intent auto refresh (s)",
        "cognitive",
        "int",
        "proxy",
        "10",
        help_text="Cache window for INTENT_MODEL=auto /running lookups. Keep short to track model swaps.",
    ),
    SettingField(
        "INTENT_CONFIDENCE_THRESHOLD",
        "Intent confidence threshold",
        "cognitive",
        "float",
        "proxy",
        "0.55",
        help_text="Minimum confidence to trust intent router label.",
    ),
    SettingField(
        "INTENT_TIMEOUT_MS",
        "Intent timeout (ms)",
        "cognitive",
        "int",
        "proxy",
        "150",
        help_text="Fail-open timeout for intent classification.",
    ),
    SettingField(
        "COGNITIVE_LATENCY_BUDGET_MS",
        "Latency budget (ms)",
        "cognitive",
        "int",
        "proxy",
        "800",
        help_text="Total pipeline time budget; stages skip when remaining time is low.",
    ),
    SettingField(
        "STAGE_BUDGET_RETRIEVE_MS",
        "Retrieve stage budget (ms)",
        "cognitive",
        "int",
        "proxy",
        "50",
        help_text="Minimum time needed to run retrieve stage.",
    ),
    SettingField(
        "STAGE_BUDGET_GRAPH_MS",
        "Graph stage budget (ms)",
        "cognitive",
        "int",
        "proxy",
        "100",
        help_text="Minimum time needed to run graph lookup stage.",
    ),
    SettingField(
        "GRAPH_DB_PATH",
        "Graph SQLite path",
        "cognitive",
        "str",
        "proxy",
        "/var/lib/rag_proxy/graph.sqlite",
        help_text="SQLite store for tier-2 graph edges.",
    ),
    SettingField(
        "GRAPH_MAX_DEPTH",
        "Graph max depth",
        "cognitive",
        "int",
        "proxy",
        "2",
        help_text="Max hops for graph expansion.",
    ),
    SettingField(
        "MEMORY_DB_PATH",
        "Rolling memory DB path",
        "cognitive",
        "str",
        "proxy",
        "/var/lib/rag_proxy/memory.sqlite",
        help_text="SQLite store for rolling conversation memory.",
    ),
    SettingField(
        "MEMORY_TTL_HOURS",
        "Memory TTL (hours)",
        "cognitive",
        "int",
        "proxy",
        "72",
        help_text="Expire memory entries after this many hours.",
    ),
    SettingField(
        "MEMORY_REFRESH_TURNS",
        "Memory refresh turns",
        "cognitive",
        "int",
        "proxy",
        "8",
        help_text="Refresh memory summary every N conversation turns.",
    ),
    # MemGraphRAG runtime (proxy env)
    SettingField(
        "ENABLE_MEMGRAPHRAG",
        "MemGraphRAG stage",
        "memgraphrag",
        "bool",
        "proxy",
        "false",
        help_text="Enable PPR graph retrieval stage (requires built SQLite index).",
    ),
    SettingField(
        "MEMGRAPHRAG_DB_PATH",
        "MemGraphRAG SQLite path",
        "memgraphrag",
        "str",
        "proxy",
        "/var/lib/rag_proxy/memgraphrag.sqlite",
        help_text="Runtime graph index built on the MemGraphRAG index build tab.",
    ),
    SettingField(
        "MEMGRAPHRAG_FACT_TOP_K",
        "Fact top K",
        "memgraphrag",
        "int",
        "proxy",
        "20",
        help_text="Facts scored before PPR graph walk.",
    ),
    SettingField(
        "MEMGRAPHRAG_PPR_DAMPING",
        "PPR damping",
        "memgraphrag",
        "float",
        "proxy",
        "0.85",
        help_text="Personalized PageRank damping factor (typically 0.85).",
    ),
    SettingField(
        "MEMGRAPHRAG_PPR_ITERATIONS",
        "PPR iterations",
        "memgraphrag",
        "int",
        "proxy",
        "20",
        help_text="PPR iteration count.",
    ),
    SettingField(
        "MEMGRAPHRAG_PASSAGE_NODE_WEIGHT",
        "Passage node weight",
        "memgraphrag",
        "float",
        "proxy",
        "0.5",
        help_text="Blend weight for passage nodes in PPR scoring.",
    ),
    SettingField(
        "STAGE_BUDGET_MEMGRAPHRAG_MS",
        "Stage budget (ms)",
        "memgraphrag",
        "int",
        "proxy",
        "200",
        help_text="Minimum time needed to run MemGraphRAG stage.",
    ),
    # MemGraphRAG offline build (sqlite only)
    SettingField(
        "MEMGRAPH_BUILD_LLM_URL",
        "Build LLM API URL",
        "memgraph_build",
        "str",
        "sqlite",
        "http://192.168.1.202:8081/v1",
        help_text="OpenAI-compatible endpoint for entity/relation extraction (remote qwen when local GPU is busy).",
    ),
    SettingField(
        "MEMGRAPH_BUILD_LLM_MODEL",
        "Build LLM model",
        "memgraph_build",
        "str",
        "sqlite",
        "qwen3.5-9b-turbo",
        help_text="Model id at the build LLM API URL.",
    ),
    SettingField(
        "MEMGRAPH_BUILD_MAX_CHUNKS",
        "Sample chunk count",
        "memgraph_build",
        "int",
        "sqlite",
        "1000",
        help_text="Max Qdrant chunks sampled for offline graph build.",
    ),
    SettingField(
        "MEMGRAPH_BUILD_CONCURRENCY",
        "Build LLM concurrency",
        "memgraph_build",
        "int",
        "sqlite",
        "3",
        help_text="Parallel LLM extraction calls during build.",
    ),
    SettingField("MEMGRAPH_BUILD_EMBED_URL", "Build embed URL", "memgraph_build", "str", "sqlite", "",
                 help_text="Blank uses EMBED_URL from ingest/proxy settings."),
    SettingField(
        "MEMGRAPH_BUILD_SKIP_RELATIONS",
        "Skip relation extraction",
        "memgraph_build",
        "bool",
        "sqlite",
        "false",
        help_text="Entities only; faster build with fewer graph edges.",
    ),
    # Observability
    SettingField(
        "LOG_LEVEL",
        "Log level",
        "observability",
        "select",
        "admin",
        "INFO",
        options=("DEBUG", "INFO", "WARNING", "ERROR"),
        help_text="rag-admin log verbosity.",
    ),
    SettingField(
        "ENABLE_REQUEST_TRACE",
        "Request traces",
        "observability",
        "bool",
        "proxy",
        "true",
        help_text="Log per-request pipeline stage summary on the proxy.",
    ),
    SettingField(
        "ENABLE_JSON_LOGS",
        "JSON pipeline logs",
        "observability",
        "bool",
        "proxy",
        "false",
        help_text="Emit structured JSON instead of text pipeline logs.",
    ),
    SettingField(
        "ENABLE_METRICS",
        "Prometheus metrics",
        "observability",
        "bool",
        "proxy",
        "false",
        help_text="Expose GET /metrics on the proxy port.",
    ),
    SettingField(
        "ENABLE_TRANSCRIPT_CAPTURE",
        "Transcript capture",
        "observability",
        "bool",
        "proxy",
        "false",
        help_text="Write finetune/RAG improvement JSONL logs (env-only extras may apply).",
    ),
)

SETTING_GROUPS: tuple[str, ...] = (
    "ingest",
    "proxy_rag",
    "cognitive",
    "memgraphrag",
    "memgraph_build",
    "observability",
)

GROUP_LABELS: dict[str, str] = {
    "ingest": "Dense ingest & BM25",
    "proxy_rag": "Proxy RAG retrieval",
    "cognitive": "Cognitive pipeline",
    "memgraphrag": "MemGraphRAG runtime",
    "memgraph_build": "MemGraphRAG index build",
    "observability": "Logging & metrics",
}

INGEST_PAUSED_KEY = "INGEST_PAUSED"

# Shared keys saved on the ingest tab are mirrored into rag-proxy.env.
INGEST_MIRROR_TO_PROXY: tuple[str, ...] = (
    "EMBED_URL",
    "QDRANT_URL",
    "QDRANT_COLLECTION",
    "SPARSE_INDEX_URL",
)
